### ISSUE TITLE
Syntax error while installing with `go get`

### ISSUE THREAD

**Issue by marthjod** [joushou/serve2d#5]
Hi @joushou, great project. Unfortunately, I am unable to install it:

```
go get github.com/joushou/serve2d
# github.com/joushou/serve2
gocode/src/github.com/joushou/serve2/serve.go:78: syntax error: unexpected range, expecting {
gocode/src/github.com/joushou/serve2/serve.go:97: non-declaration statement outside function body
gocode/src/github.com/joushou/serve2/serve.go:99: non-declaration statement outside function body
gocode/src/github.com/joushou/serve2/serve.go:107: non-declaration statement outside function body
gocode/src/github.com/joushou/serve2/serve.go:108: syntax error: unexpected }
# github.com/joushou/serve2/proto
gocode/src/github.com/joushou/serve2/proto/tlsmatcher.go:114: cs.Version undefined (type tls.ConnectionState has no field or method Version)
```

Same on _go version go1.2 linux/arm_ and _go version go1.2 linux/amd64_.

**Comment by kennylevinsen** [comment]
Thanks for liking the project!

I suspect that the issue is on your end, however. Serve2d is built using the latest releases of Go, meaning 1.4.2 and 1.5rc1. I believe the errors you are receiving are because of syntactic constructs that weren't added till 1.3 and 1.4.

Are you able to upgrade to at least 1.4.2? If your distribution has no official way to install, consider either using "gimme" (https://github.com/travis-ci/gimme/ - what TravisCI uses), "gvm" (https://github.com/moovweb/gvm), or just installation from source which is _super_ simple. 1.2 is quite outdated. I can also add more binaries to the release if you'd like.

If you want to code go yourself, I heavily suggest updating so that you get the convenience features, bugfixes and performance of 1.4.2 or 1.5rc1.

**Comment by kennylevinsen** [comment]
I've added 1.4.2 as a requirement under "Installation", to avoid future confusion. Thanks for pointing it out that this was lacking, btw.

When you've gotten things to work, or you need more guidance, comment on the issue. I'll close it when things seem to be working for you, or I haven't heard from you long enough.

**Comment by marthjod** [comment]
Hey, thanks for the quick response. 

Yes, I already suspected that my version was too old. I normally use current-stable versions as well, but I'd love to have Serve2d running on a Raspberry Pi, where installing Go hasn't been that straightforward last time. But I'll try with 1.4+.

Issue can be closed imho, since you mention the required version now. Thanks again.

**Comment by kennylevinsen** [comment]
In go1.5rc1, boostrapping the toolschains for cross-compilation is as easy as calling make.bash with GOOS and GOARCH set to things like "linux" and "arm", making the actual cross-compilation for Rasberry Pi "GOOS=linux GOARCH=arm go build".

It does require that Go was built from source (which gimme, gvm, and homebrew (OS X) does), as the package would otherwise have to bundle the cross-compilation suite as well.

If you can wait two minutes, I'll upload a linux/arm build to the v0.3 release zips. It's built from OS X, so there's no cgo, but tell me if it works.

**Comment by kennylevinsen** [comment]
Uploaded: https://github.com/joushou/serve2d/releases
Try it and tell me if it works!

**Comment by marthjod** [comment]
Yes, I've got it working on the Pi with your latest ARM binary, thanks a lot :).

Two small remarks:
- When using the example JSON from the README instead of _example_conf.json_ in the source code zip, serve2d exits silently after reading the config (afaics, it doesn't like the _logFile_ param).
- Also, it seems to have trouble parsing any config file comments ("invalid character '/' looking for beginning of object key string" etc.).

**Comment by kennylevinsen** [comment]
Ah, right. See, those comments are for documentary purposes. JSON, in any form, doesn't actually support comments, so if you copy paste the thing from the README, the JSON parser in Go will commit harakiri. :(

... It should, however, notice that the logging framework has not yet been set up, and error out to stderr. That, I believe, is what my setups usually do if I screw up the config. I'll take a look at it, though.

logFile does work - that's how I run my own servers! It looks sane to me, although do remember that it's relative to the current working directory, so it will need to be able to make files in the working directory, or write permissions to the file if it already exists. I have absolute paths as logFile paths for that reason, and touched and chmodded the logfile before use, so it can be in /var/log where the serve2d user wouldn't normally have permissions to make files.
